name: Workflow of tools.simpleweb3

on:
  push:
    branches: [main] 
  workflow_dispatch:  

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: false

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  

  deploy:
    name: Deploy to GitHub
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy Site to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
